version: '3.8'

services:
  app:
    build: .
    container_name: smart-helpdesk-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/helpdeskdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - helpdesk-network

  db:
    image: postgres:15-alpine
    container_name: smart-helpdesk-db
    restart: always
    environment:
      - POSTGRES_DB=helpdeskdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - helpdesk-network

  frontend:
    build: ./frontend
    container_name: smart-helpdesk-frontend
    ports:
      - "4200:80"
    networks:
      - helpdesk-network

volumes:
  db_data:

networks:
  helpdesk-network: