version: '3.8'
services:
  db:
    image: postgres:15
    container_name: helpdesk_db
    environment:
      POSTGRES_USER: helpdesk
      POSTGRES_PASSWORD: password
      POSTGRES_DB: helpdesk_db
    ports:
      - "5432:5432"